name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        platform: [ubuntu, windows, macos]
        profile: [dev, release]

    runs-on: ${{ matrix.platform }}--latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --locked --verbose --profile=${{ matrix.profile }}
    - name: Run tests
      run: cargo test --locked --verbose --profile=${{ matrix.profile }}
